### ISSUE TITLE
Replacement of Tf-Idf Vectorisation with Word Embeddings

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/newsnow#2]
It would be great to have multiple methods of word embeddings available to enhance the functionality. These can include - 

- Word2Vec
- fastText
- ELMo

If you are working on any, do leave a comment for others to know.

**Comment by bhadreshpsavani** [comment]
I can work on Word2Vec

**Comment by sakares** [comment]
Hi @aditeyabaral 

In order to participate **_hacktoberfest2021_**  , 
may I take this issue and will send you PR back soon? Thanks

**Comment by aditeyabaral** [comment]
@sakares Sure!

**Comment by sakares** [comment]
Feel free to check the PR #5
